### ISSUE TITLE
Litho (Milestone 1)

### ISSUE THREAD

**Issue by jordy25519** [cennznet/grants#4]
Bounty Description  
---

Build the interface for Litho, a digital asset marketplace for the CENNZnet blockchain that allows users to create, mint and view both generic assets (fungible tokens) and NFTs (collectible tokens).   

This bounty includes the front-end design and implementation of the interface and integration with the CENNZnet wallet extension.   

  

Context  
---

CENNZnet is a public blockchain and Decentralised Application platform that puts a great user experience first. CENNZnet needs an equally great interface for Litho, so that the creation of digital assets on the CENNZnet blockchain is seamless.  

Learn more: cennznet.io   

## Create a single NFT (Milestone 1) 

This grant will be completed across multiple milestones.
The first grant will enable:
- Simple landing page  
- Simple navigation  
- User can connect to the CENNZnet wallet browser extension  
- Allow a user to create a single NFT with title, description, attributes and any relevant imagery  
- Allow a user to set royalties for their NFT 
- Allow a user to choose the content storage they’d like to publish their NFT to (if applicable) 
- Allow a user to view an NFT they’ve created  

## Resources

Overview of the module: https://medium.com/centrality/introducing-the-cennznet-nft-module-c1ce3ed79840

API technical reference here: https://github.com/cennznet/api.js/blob/master/docs/cennznet/extrinsics.md#nft

Module rust reference here: https://github.com/cennznet/cennznet/blob/develop/crml/nft/src/lib.rs

wiki guides: https://wiki.cennz.net/

Interface design will be provided

**Comment by gitcoinbot** [comment]
Issue Status: 1. **Open** 2. Started 3. Submitted 4. Done 

<hr>

__This issue now has a funding of 5000.0 DAI (5000.0 USD @ $1.0/DAI)  attached to it as part of the Centrality CENNZnet fund.__

 * If you would like to work on this issue you can 'start work' [on the Gitcoin Issue Details page](https://gitcoin.co/issue/cennznet/grants/4/100025771).
* Want to chip in? Add your own contribution [here](https://gitcoin.co/issue/cennznet/grants/4/100025771).
* Questions? Checkout <a href='https://gitcoin.co/help'>Gitcoin Help</a> or the <a href='https://discord.gg/gitcoin/'>Gitcoin's Discord</a>
* $1,705,745.29 more funded OSS Work available on the [Gitcoin Issue Explorer](https://gitcoin.co/explorer)

**Comment by gitcoinbot** [comment]
Issue Status: 1. Open 2. **Started** 3. Submitted 4. Done 

<hr>

__Work has been started__.


These users each claimed they can complete the work by 265 years, 5 months from now.
Please review their action plans below:


**1) [dragonking725](https://gitcoin.co/dragonking725) has applied to start work _(Funders only: [approve worker](https://gitcoin.co/issue/cennznet/grants/4/100025771?mutate_worker_action=approve&worker=dragonking725) | [reject worker](https://gitcoin.co/issue/cennznet/grants/4/100025771?mutate_worker_action=reject&worker=dragonking725))_.**

The Chinese version of the page needs to be added。
**2) [hafeezrai](https://gitcoin.co/hafeezrai) has applied to start work _(Funders only: [approve worker](https://gitcoin.co/issue/cennznet/grants/4/100025771?mutate_worker_action=approve&worker=hafeezrai) | [reject worker](https://gitcoin.co/issue/cennznet/grants/4/100025771?mutate_worker_action=reject&worker=hafeezrai))_.**

Action Plan:
1: Complete Frontend Design prototype(including Landing page and NFT pages)
2: Landing Page
3: NFT related pages
**3) [sjdb123](https://gitcoin.co/sjdb123) has applied to start work _(Funders only: [approve worker](https://gitcoin.co/issue/cennznet/grants/4/100025771?mutate_worker_action=approve&worker=sjdb123) | [reject worker](https://gitcoin.co/issue/cennznet/grants/4/100025771?mutate_worker_action=reject&worker=sjdb123))_.**

加油，项目应该长远发展，-，，，，，，   ，，，，，，，，，，，，，
**4) [purel99](https://gitcoin.co/purel99) has applied to start work _(Funders only: [approve worker](https://gitcoin.co/issue/cennznet/grants/4/100025771?mutate_worker_action=approve&worker=purel99) | [reject worker](https://gitcoin.co/issue/cennznet/grants/4/100025771?mutate_worker_action=reject&worker=purel99))_.**

Thanks for giving us such a great opportunity. I am supporting it. always success for the development team to the moon
**5) [bazeey](https://gitcoin.co/bazeey) has applied to start work _(Funders only: [approve worker](https://gitcoin.co/issue/cennznet/grants/4/100025771?mutate_worker_action=approve&worker=bazeey) | [reject worker](https://gitcoin.co/issue/cennznet/grants/4/100025771?mutate_worker_action=reject&worker=bazeey))_.**

Maximise the opportunity to achieve its full potentials
**6) [yxj73777](https://gitcoin.co/yxj73777) has applied to start work _(Funders only: [approve worker](https://gitcoin.co/issue/cennznet/grants/4/100025771?mutate_worker_action=approve&worker=yxj73777) | [reject worker](https://gitcoin.co/issue/cennznet/grants/4/100025771?mutate_worker_action=reject&worker=yxj73777))_.**

Together, we're happy to change the status quo
**7) [wahyu98](https://gitcoin.co/wahyu98) has applied to start work _(Funders only: [approve worker](https://gitcoin.co/issue/cennznet/grants/4/100025771?mutate_worker_action=approve&worker=wahyu98) | [reject worker](https://gitcoin.co/issue/cennznet/grants/4/100025771?mutate_worker_action=reject&worker=wahyu98))_.**

Nice Project and good... I like this
**8) [putradham](https://gitcoin.co/putradham) has applied to start work _(Funders only: [approve worker](https://gitcoin.co/issue/cennznet/grants/4/100025771?mutate_worker_action=approve&worker=putradham) | [reject worker](https://gitcoin.co/issue/cennznet/grants/4/100025771?mutate_worker_action=reject&worker=putradham))_.**

Gasken aja bro, tidak suka bacot bacot
**9) [trangcop](https://gitcoin.co/trangcop) has applied to start work _(Funders only: [approve worker](https://gitcoin.co/issue/cennznet/grants/4/100025771?mutate_worker_action=approve&worker=trangcop) | [reject worker](https://gitcoin.co/issue/cennznet/grants/4/100025771?mutate_worker_action=reject&worker=trangcop))_.**

Plan 1: Add the best NTf item
 Plan 2: Navigate NFTs with the same content.
**10) [shad-k](https://gitcoin.co/shad-k) has been approved to start work.**

I can implement a NextJS or CRA React Single Page App. The application will be responsive and performant and will cover all the points mentioned in the milestone.
I am Frontend Engineer with 5+ years of experience building scalable, responsive and performant frontend web applications.
**11) [saviabasil](https://gitcoin.co/saviabasil) has applied to start work _(Funders only: [approve worker](https://gitcoin.co/issue/cennznet/grants/4/100025771?mutate_worker_action=approve&worker=saviabasil) | [reject worker](https://gitcoin.co/issue/cennznet/grants/4/100025771?mutate_worker_action=reject&worker=saviabasil))_.**

I will deploy my digital skills to take on this project
**12) [juice333](https://gitcoin.co/juice333) has applied to start work _(Funders only: [approve worker](https://gitcoin.co/issue/cennznet/grants/4/100025771?mutate_worker_action=approve&worker=juice333) | [reject worker](https://gitcoin.co/issue/cennznet/grants/4/100025771?mutate_worker_action=reject&worker=juice333))_.**

Will take some attention on this project and willing to go further
**13) [19110401125](https://gitcoin.co/19110401125) has applied to start work _(Funders only: [approve worker](https://gitcoin.co/issue/cennznet/grants/4/100025771?mutate_worker_action=approve&worker=19110401125) | [reject worker](https://gitcoin.co/issue/cennznet/grants/4/100025771?mutate_worker_action=reject&worker=19110401125))_.**

没看明白，I DON'Tsee  understand！letter enough
**14) [jayday55](https://gitcoin.co/jayday55) has applied to start work _(Funders only: [approve worker](https://gitcoin.co/issue/cennznet/grants/4/100025771?mutate_worker_action=approve&worker=jayday55) | [reject worker](https://gitcoin.co/issue/cennznet/grants/4/100025771?mutate_worker_action=reject&worker=jayday55))_.**

Do the first step to make sure I was share it to all my friends and above and beyond and keep sharing it until it goes viral my next step is to make sure and maintain the marketing skills that I provide to myself and my team to make sure everything you going to be a curly to plan
**15) [ryan170399](https://gitcoin.co/ryan170399) has applied to start work _(Funders only: [approve worker](https://gitcoin.co/issue/cennznet/grants/4/100025771?mutate_worker_action=approve&worker=ryan170399) | [reject worker](https://gitcoin.co/issue/cennznet/grants/4/100025771?mutate_worker_action=reject&worker=ryan170399))_.**

add best nft items
Add cross chain
**16) [nwyler-modusagency](https://gitcoin.co/nwyler-modusagency) has applied to start work _(Funders only: [approve worker](https://gitcoin.co/issue/cennznet/grants/4/100025771?mutate_worker_action=approve&worker=nwyler-modusagency) | [reject worker](https://gitcoin.co/issue/cennznet/grants/4/100025771?mutate_worker_action=reject&worker=nwyler-modusagency))_.**

- Design Review, comments, and improvements from a Front End Engineer 
- Specs, break the design into reusable components and static ones
- work planning and estimations
- start development
**17) [canh130798](https://gitcoin.co/canh130798) has applied to start work _(Funders only: [approve worker](https://gitcoin.co/issue/cennznet/grants/4/100025771?mutate_worker_action=approve&worker=canh130798) | [reject worker](https://gitcoin.co/issue/cennznet/grants/4/100025771?mutate_worker_action=reject&worker=canh130798))_.**

Visit web, create my address an join the NFT showroom
**18) [fbenwu](https://gitcoin.co/fbenwu) has applied to start work _(Funders only: [approve worker](https://gitcoin.co/issue/cennznet/grants/4/100025771?mutate_worker_action=approve&worker=fbenwu) | [reject worker](https://gitcoin.co/issue/cennznet/grants/4/100025771?mutate_worker_action=reject&worker=fbenwu))_.**

The Chinese version of the page needs to be added。
**19) [huudat88](https://gitcoin.co/huudat88) has applied to start work _(Funders only: [approve worker](https://gitcoin.co/issue/cennznet/grants/4/100025771?mutate_worker_action=approve&worker=huudat88) | [reject worker](https://gitcoin.co/issue/cennznet/grants/4/100025771?mutate_worker_action=reject&worker=huudat88))_.**

Nice Project and good... I like this
**20) [blcold](https://gitcoin.co/blcold) has applied to start work _(Funders only: [approve worker](https://gitcoin.co/issue/cennznet/grants/4/100025771?mutate_worker_action=approve&worker=blcold) | [reject worker](https://gitcoin.co/issue/cennznet/grants/4/100025771?mutate_worker_action=reject&worker=blcold))_.**

Simple landing page
Simple navigation
User can connect to the CENNZnet wallet browser extension
Allow a user to create a single NFT with title, description, attributes and any relevant imagery
Allow a user to set royalties for their NFT
Allow a user to choose the content storage they’d like to publish their NFT to (if applicable)
Allow a user to view an NFT they’ve created
**21) [jauhary123](https://gitcoin.co/jauhary123) has applied to start work _(Funders only: [approve worker](https://gitcoin.co/issue/cennznet/grants/4/100025771?mutate_worker_action=approve&worker=jauhary123) | [reject worker](https://gitcoin.co/issue/cennznet/grants/4/100025771?mutate_worker_action=reject&worker=jauhary123))_.**

Gitcoin is beauty coin for trade.
Moon moon moon
**22) [denisetiaonez](https://gitcoin.co/denisetiaonez) has applied to start work _(Funders only: [approve worker](https://gitcoin.co/issue/cennznet/grants/4/100025771?mutate_worker_action=approve&worker=denisetiaonez) | [reject worker](https://gitcoin.co/issue/cennznet/grants/4/100025771?mutate_worker_action=reject&worker=denisetiaonez))_.**

I love art and NFT is one of the important things in the new era of art in future, looks like the future is very bright here.
**23) [jatnika81](https://gitcoin.co/jatnika81) has applied to start work _(Funders only: [approve worker](https://gitcoin.co/issue/cennznet/grants/4/100025771?mutate_worker_action=approve&worker=jatnika81) | [reject worker](https://gitcoin.co/issue/cennznet/grants/4/100025771?mutate_worker_action=reject&worker=jatnika81))_.**

This project must accepted and reflected to paying in matketplace
**24) [matzelele89](https://gitcoin.co/matzelele89) has applied to start work _(Funders only: [approve worker](https://gitcoin.co/issue/cennznet/grants/4/100025771?mutate_worker_action=approve&worker=matzelele89) | [reject worker](https://gitcoin.co/issue/cennznet/grants/4/100025771?mutate_worker_action=reject&worker=matzelele89))_.**

Ich werde mir Mühe geben so viel wie möglich zu ernten
**25) [nicholas0071234](https://gitcoin.co/nicholas0071234) has applied to start work _(Funders only: [approve worker](https://gitcoin.co/issue/cennznet/grants/4/100025771?mutate_worker_action=approve&worker=nicholas0071234) | [reject worker](https://gitcoin.co/issue/cennznet/grants/4/100025771?mutate_worker_action=reject&worker=nicholas0071234))_.**

Let me get this to work on seems like a lot of fun
**26) [skynnpr](https://gitcoin.co/skynnpr) has applied to start work _(Funders only: [approve worker](https://gitcoin.co/issue/cennznet/grants/4/100025771?mutate_worker_action=approve&worker=skynnpr) | [reject worker](https://gitcoin.co/issue/cennznet/grants/4/100025771?mutate_worker_action=reject&worker=skynnpr))_.**

Just try it ,make the best for it.
**27) [alinawaz007](https://gitcoin.co/alinawaz007) has applied to start work _(Funders only: [approve worker](https://gitcoin.co/issue/cennznet/grants/4/100025771?mutate_worker_action=approve&worker=alinawaz007) | [reject worker](https://gitcoin.co/issue/cennznet/grants/4/100025771?mutate_worker_action=reject&worker=alinawaz007))_.**

Add Nft items from lower to higher catogory wise
**28) [donzq](https://gitcoin.co/donzq) has applied to start work _(Funders only: [approve worker](https://gitcoin.co/issue/cennznet/grants/4/100025771?mutate_worker_action=approve&worker=donzq) | [reject worker](https://gitcoin.co/issue/cennznet/grants/4/100025771?mutate_worker_action=reject&worker=donzq))_.**

its great project.
but there should have the Chinese version of the page .
**29) [sarath6080](https://gitcoin.co/sarath6080) has applied to start work _(Funders only: [approve worker](https://gitcoin.co/issue/cennznet/grants/4/100025771?mutate_worker_action=approve&worker=sarath6080) | [reject worker](https://gitcoin.co/issue/cennznet/grants/4/100025771?mutate_worker_action=reject&worker=sarath6080))_.**

1. Plan the project
2. Develop
3. test
4. test
**30) [sarasioux](https://gitcoin.co/sarasioux) has applied to start work _(Funders only: [approve worker](https://gitcoin.co/issue/cennznet/grants/4/100025771?mutate_worker_action=approve&worker=sarasioux) | [reject worker](https://gitcoin.co/issue/cennznet/grants/4/100025771?mutate_worker_action=reject&worker=sarasioux))_.**

I would build the UI in Vue.  The content management of NFTs is simple and straightforward, the integration with the wallet might be a bit challenging as I've never done it before (only Metamask) but I think I can tackle it.  I am heavy on good UI/UX so it would have great usability.  I am not heavy on design so it will be ready for skinning.
**31) [yopihfadilah1](https://gitcoin.co/yopihfadilah1) has applied to start work _(Funders only: [approve worker](https://gitcoin.co/issue/cennznet/grants/4/100025771?mutate_worker_action=approve&worker=yopihfadilah1) | [reject worker](https://gitcoin.co/issue/cennznet/grants/4/100025771?mutate_worker_action=reject&worker=yopihfadilah1))_.**

I really understand this project, and I like it.
**32) [tifani19](https://gitcoin.co/tifani19) has applied to start work _(Funders only: [approve worker](https://gitcoin.co/issue/cennznet/grants/4/100025771?mutate_worker_action=approve&worker=tifani19) | [reject worker](https://gitcoin.co/issue/cennznet/grants/4/100025771?mutate_worker_action=reject&worker=tifani19))_.**

Tambahkan berbagai bahasa, khususnya bahasa indonesia agar mudah difahami dan dikenal masyarakat luas
**33) [rittylov](https://gitcoin.co/rittylov) has applied to start work _(Funders only: [approve worker](https://gitcoin.co/issue/cennznet/grants/4/100025771?mutate_worker_action=approve&worker=rittylov) | [reject worker](https://gitcoin.co/issue/cennznet/grants/4/100025771?mutate_worker_action=reject&worker=rittylov))_.**

Thank you so much for this. I love it!
**34) [schehata](https://gitcoin.co/schehata) has applied to start work _(Funders only: [approve worker](https://gitcoin.co/issue/cennznet/grants/4/100025771?mutate_worker_action=approve&worker=schehata) | [reject worker](https://gitcoin.co/issue/cennznet/grants/4/100025771?mutate_worker_action=reject&worker=schehata))_.**

Hi there,

I am interested in working on this, I have frontend experience, especially with VueJS, if thats one of the options you would consider.

I have a question though, this is a single page app, or should it support Server Side Rendering? (to work correctly with web crawlers and provide correct SEO metadata and so on)
**35) [noyjacker](https://gitcoin.co/noyjacker) has applied to start work _(Funders only: [approve worker](https://gitcoin.co/issue/cennznet/grants/4/100025771?mutate_worker_action=approve&worker=noyjacker) | [reject worker](https://gitcoin.co/issue/cennznet/grants/4/100025771?mutate_worker_action=reject&worker=noyjacker))_.**

how much CNNZ does it cost to make NFT itself?
**36) [adoniece](https://gitcoin.co/adoniece) has applied to start work _(Funders only: [approve worker](https://gitcoin.co/issue/cennznet/grants/4/100025771?mutate_worker_action=approve&worker=adoniece) | [reject worker](https://gitcoin.co/issue/cennznet/grants/4/100025771?mutate_worker_action=reject&worker=adoniece))_.**

make quick and fast decision about about handling my task
**37) [mahlill](https://gitcoin.co/mahlill) has applied to start work _(Funders only: [approve worker](https://gitcoin.co/issue/cennznet/grants/4/100025771?mutate_worker_action=approve&worker=mahlill) | [reject worker](https://gitcoin.co/issue/cennznet/grants/4/100025771?mutate_worker_action=reject&worker=mahlill))_.**

I saya suka dengan voin ini semiga beruntung
**38) [36nerecan36](https://gitcoin.co/36nerecan36) has applied to start work _(Funders only: [approve worker](https://gitcoin.co/issue/cennznet/grants/4/100025771?mutate_worker_action=approve&worker=36nerecan36) | [reject worker](https://gitcoin.co/issue/cennznet/grants/4/100025771?mutate_worker_action=reject&worker=36nerecan36))_.**

Telegram Twitter görevleri yapıcam
**39) [ionut25xd](https://gitcoin.co/ionut25xd) has applied to start work _(Funders only: [approve worker](https://gitcoin.co/issue/cennznet/grants/4/100025771?mutate_worker_action=approve&worker=ionut25xd) | [reject worker](https://gitcoin.co/issue/cennznet/grants/4/100025771?mutate_worker_action=reject&worker=ionut25xd))_.**

Thanks for giving us such a great opportunity. I am supporting it
**40) [chacing](https://gitcoin.co/chacing) has applied to start work _(Funders only: [approve worker](https://gitcoin.co/issue/cennznet/grants/4/100025771?mutate_worker_action=approve&worker=chacing) | [reject worker](https://gitcoin.co/issue/cennznet/grants/4/100025771?mutate_worker_action=reject&worker=chacing))_.**

I believe this is a faithful project.The projector has a lot of attractions so hopefully the project will be better in the future and will be the best.
I love it
**41) [cookie1pop](https://gitcoin.co/cookie1pop) has applied to start work _(Funders only: [approve worker](https://gitcoin.co/issue/cennznet/grants/4/100025771?mutate_worker_action=approve&worker=cookie1pop) | [reject worker](https://gitcoin.co/issue/cennznet/grants/4/100025771?mutate_worker_action=reject&worker=cookie1pop))_.**

666666666666666666666666666666666666666666666
**42) [xayaan](https://gitcoin.co/xayaan) has applied to start work _(Funders only: [approve worker](https://gitcoin.co/issue/cennznet/grants/4/100025771?mutate_worker_action=approve&worker=xayaan) | [reject worker](https://gitcoin.co/issue/cennznet/grants/4/100025771?mutate_worker_action=reject&worker=xayaan))_.**

I will develop as requested in the scope within the least required time.
**43) [18530027142](https://gitcoin.co/18530027142) has applied to start work _(Funders only: [approve worker](https://gitcoin.co/issue/cennznet/grants/4/100025771?mutate_worker_action=approve&worker=18530027142) | [reject worker](https://gitcoin.co/issue/cennznet/grants/4/100025771?mutate_worker_action=reject&worker=18530027142))_.**

测试测试测试测试测试测试测试测试测试测试测试测试测试测试测试测试测试测试测试测试测试测试测试测试测试测试测试测试测试测试测试测试测试测试测试测试测试测试测试测试测试测试测试测试测试测试测试测试测试测试测试测试测试
**44) [gitcoindeveloper](https://gitcoin.co/gitcoindeveloper) has applied to start work _(Funders only: [approve worker](https://gitcoin.co/issue/cennznet/grants/4/100025771?mutate_worker_action=approve&worker=gitcoindeveloper) | [reject worker](https://gitcoin.co/issue/cennznet/grants/4/100025771?mutate_worker_action=reject&worker=gitcoindeveloper))_.**

MILESTONE-1)

I WILL CREATE NFT MARKETPLACE WITH SIMPLE LANDING PAGE AND NAVIGATION THAT WILL CONNECT TO CENNZnet wallet browser extension , AND USERS CAN CREATE NFT with title, description, attributes and any relevant imagery.

THANK YOU
ITS A GREAT OPPORTUNITY FOR ME TO ADVANCE MY SKILLS IN BLOCKCHAIN.

Learn more [on the Gitcoin Issue Details page](https://gitcoin.co/issue/cennznet/grants/4/100025771).

**Comment by gitcoinbot** [comment]
@shad-k Hello from Gitcoin Core - are you still working on this issue? Please submit a WIP PR or comment back within the next 3 days or you will be removed from this ticket and it will be returned to an ‘Open’ status. Please let us know if you have questions!
* [x] reminder (3 days)
* [ ] escalation to mods (6 days)

Funders only: Snooze warnings for [1 day](https://gitcoin.co/issue/cennznet/grants/4/100025771?snooze=1) | [3 days](https://gitcoin.co/issue/cennznet/grants/4/100025771?snooze=3) | [5 days](https://gitcoin.co/issue/cennznet/grants/4/100025771?snooze=5) | [10 days](https://gitcoin.co/issue/cennznet/grants/4/100025771?snooze=10) | [100 days](https://gitcoin.co/issue/cennznet/grants/4/100025771?snooze=100)

**Comment by shad-k** [comment]
Working on it. Got the designs today.

**Comment by gitcoinbot** [comment]
@shad-k Hello from Gitcoin Core - are you still working on this issue? Please submit a WIP PR or comment back within the next 3 days or you will be removed from this ticket and it will be returned to an ‘Open’ status. Please let us know if you have questions!
* [x] reminder (3 days)
* [ ] escalation to mods (6 days)

Funders only: Snooze warnings for [1 day](https://gitcoin.co/issue/cennznet/grants/4/100025771?snooze=1) | [3 days](https://gitcoin.co/issue/cennznet/grants/4/100025771?snooze=3) | [5 days](https://gitcoin.co/issue/cennznet/grants/4/100025771?snooze=5) | [10 days](https://gitcoin.co/issue/cennznet/grants/4/100025771?snooze=10) | [100 days](https://gitcoin.co/issue/cennznet/grants/4/100025771?snooze=100)

**Comment by shad-k** [comment]
I have started with the work and the home page UI is done. Waiting for some of the assets that would go on to the homepage.
Now looking at connecting the wallet extension to the app and then will start working on the create NFT flows.

**Comment by shad-k** [comment]
Another update: Wallet extension connected. Now integrating with the API to mint and fetch NFTs.

**Comment by gitcoinbot** [comment]
@shad-k Hello from Gitcoin Core - are you still working on this issue? Please submit a WIP PR or comment back within the next 3 days or you will be removed from this ticket and it will be returned to an ‘Open’ status. Please let us know if you have questions!
* [x] reminder (3 days)
* [ ] escalation to mods (6 days)

Funders only: Snooze warnings for [1 day](https://gitcoin.co/issue/cennznet/grants/4/100025771?snooze=1) | [3 days](https://gitcoin.co/issue/cennznet/grants/4/100025771?snooze=3) | [5 days](https://gitcoin.co/issue/cennznet/grants/4/100025771?snooze=5) | [10 days](https://gitcoin.co/issue/cennznet/grants/4/100025771?snooze=10) | [100 days](https://gitcoin.co/issue/cennznet/grants/4/100025771?snooze=100)

**Comment by shad-k** [comment]
Finished some design related grunt work. Also finishing up the API integration.

**Comment by gitcoinbot** [comment]
@shad-k Hello from Gitcoin Core - are you still working on this issue? Please submit a WIP PR or comment back within the next 3 days or you will be removed from this ticket and it will be returned to an ‘Open’ status. Please let us know if you have questions!
* [x] reminder (3 days)
* [ ] escalation to mods (6 days)

Funders only: Snooze warnings for [1 day](https://gitcoin.co/issue/cennznet/grants/4/100025771?snooze=1) | [3 days](https://gitcoin.co/issue/cennznet/grants/4/100025771?snooze=3) | [5 days](https://gitcoin.co/issue/cennznet/grants/4/100025771?snooze=5) | [10 days](https://gitcoin.co/issue/cennznet/grants/4/100025771?snooze=10) | [100 days](https://gitcoin.co/issue/cennznet/grants/4/100025771?snooze=100)

**Comment by shad-k** [comment]
Yes, on it. Done with the UI, working my way through some integration issues.

**Comment by shad-k** [comment]
In the final stages of development. Will share a preview link with code repo soon.

**Comment by gitcoinbot** [comment]
@shad-k Hello from Gitcoin Core - are you still working on this issue? Please submit a WIP PR or comment back within the next 3 days or you will be removed from this ticket and it will be returned to an ‘Open’ status. Please let us know if you have questions!
* [x] reminder (3 days)
* [ ] escalation to mods (6 days)

Funders only: Snooze warnings for [1 day](https://gitcoin.co/issue/cennznet/grants/4/100025771?snooze=1) | [3 days](https://gitcoin.co/issue/cennznet/grants/4/100025771?snooze=3) | [5 days](https://gitcoin.co/issue/cennznet/grants/4/100025771?snooze=5) | [10 days](https://gitcoin.co/issue/cennznet/grants/4/100025771?snooze=10) | [100 days](https://gitcoin.co/issue/cennznet/grants/4/100025771?snooze=100)

**Comment by shad-k** [comment]
Major dev work is done. Will be scheduling a demo this week. Preview can be viewed here: https://litho-hk4xzfrmv-shad-k.vercel.app/

Some assets are yet to be provided, will add as soon as they are available.

**Comment by gitcoinbot** [comment]
@shad-k Hello from Gitcoin Core - are you still working on this issue? Please submit a WIP PR or comment back within the next 3 days or you will be removed from this ticket and it will be returned to an ‘Open’ status. Please let us know if you have questions!
* [x] reminder (3 days)
* [ ] escalation to mods (6 days)

Funders only: Snooze warnings for [1 day](https://gitcoin.co/issue/cennznet/grants/4/100025771?snooze=1) | [3 days](https://gitcoin.co/issue/cennznet/grants/4/100025771?snooze=3) | [5 days](https://gitcoin.co/issue/cennznet/grants/4/100025771?snooze=5) | [10 days](https://gitcoin.co/issue/cennznet/grants/4/100025771?snooze=10) | [100 days](https://gitcoin.co/issue/cennznet/grants/4/100025771?snooze=100)

**Comment by shad-k** [comment]
Working on certain aspects discussed in the demo meeting.

**Comment by shad-k** [comment]
Had to rewrite parts of the application to incorporate the feedback. Currently working on supporting all kinds of file uploads.

**Comment by Amy-Centrality** [comment]
Hey guys, we'd like to qualify for GitBook free hosting for open source projects. Could you please add the following?
- Have a README.md file
- Have a CONTRIBUTING.md file
- Have a CODE_OF_CONDUCT.md file

**Comment by shad-k** [comment]
@Amy-Centrality would you like me to mention anything specific in any of the files?

**Comment by neonflux-io** [comment]
Hi @jordy25519, I’m interested in helping with Litho or related CENNZnet NFT tooling.

I have experience with React/Next.js, TypeScript, Web3 wallet integrations, NFT minting flows, marketplaces, and frontend/backend integration. If Litho is still maintained, I’d be happy to help with updates, bug fixes, wallet/API integration, or new marketplace features.

Are there any current tasks or milestones that need another contributor?
