### ISSUE TITLE
Litho (Milestone 2)

### ISSUE THREAD

**Issue by cennznet-bounties** [cennznet/grants#6]
### Bounty Description  
Build the interface for Litho-Mart, a digital asset marketplace for the CENNZnet blockchain that allows users to search, view, store, buy and sell NFTs (collectible tokens).   
This bounty includes the front-end design and implementation of the market interface. 

### Context
CENNZnet is a public blockchain and Decentralised Application platform that puts a great user experience first. CENNZnet needs an equally great interface for Litho, so that the creation of digital assets on the CENNZnet blockchain is seamless.  

Learn more: cennznet.io    
 
### Milestone 2 – Browse
This grant will be completed across multiple milestones.
The second grant will enable:
- View all NFTs that have been listed and display content
    - Image
    - Creator
- Search/filter/sort NFTs  
- Simple FAQ page  
- Profile
- My items
- Featured NFT  of the week

------ 
### Resources
Overview of the module: https://medium.com/centrality/introducing-the-cennznet-nft-module-c1ce3ed79840

API technical reference here: https://github.com/cennznet/api.js/blob/master/docs/cennznet/extrinsics.md#nft

Module rust reference here: https://github.com/cennznet/cennznet/blob/develop/crml/nft/src/lib.rs

wiki guides: https://wiki.cennz.net/

Interface design will be provided

**Comment by gitcoinbot** [comment]
Issue Status: 1. **Open** 2. Started 3. Submitted 4. Done 

<hr>

__This issue now has a funding of 5000.0 DAI (5000.0 USD @ $1.0/DAI)  attached to it as part of the CENNZnet fund.__

 * If you would like to work on this issue you can 'start work' [on the Gitcoin Issue Details page](https://gitcoin.co/issue/cennznet/grants/6/100025997).
* Want to chip in? Add your own contribution [here](https://gitcoin.co/issue/cennznet/grants/6/100025997).
* Questions? Checkout <a href='https://gitcoin.co/help'>Gitcoin Help</a> or the <a href='https://discord.gg/gitcoin/'>Gitcoin's Discord</a>
* $2,098,096.63 more funded OSS Work available on the [Gitcoin Issue Explorer](https://gitcoin.co/explorer)

**Comment by gitcoinbot** [comment]
Issue Status: 1. Open 2. **Started** 3. Submitted 4. Done 

<hr>

__Work has been started__.


These users each claimed they can complete the work by 265 years, 4 months from now.
Please review their action plans below:


**1) [mobiledev-111-118](https://gitcoin.co/mobiledev-111-118) has applied to start work _(Funders only: [approve worker](https://gitcoin.co/issue/cennznet/grants/6/100025997?mutate_worker_action=approve&worker=mobiledev-111-118) | [reject worker](https://gitcoin.co/issue/cennznet/grants/6/100025997?mutate_worker_action=reject&worker=mobiledev-111-118))_.**

Interest in this job. Lets have more chat in Telegram: @MDExpert
**2) [nguyenvanan95](https://gitcoin.co/nguyenvanan95) has applied to start work _(Funders only: [approve worker](https://gitcoin.co/issue/cennznet/grants/6/100025997?mutate_worker_action=approve&worker=nguyenvanan95) | [reject worker](https://gitcoin.co/issue/cennznet/grants/6/100025997?mutate_worker_action=reject&worker=nguyenvanan95))_.**

I think the project is good for the community
**3) [wweagle09](https://gitcoin.co/wweagle09) has applied to start work _(Funders only: [approve worker](https://gitcoin.co/issue/cennznet/grants/6/100025997?mutate_worker_action=approve&worker=wweagle09) | [reject worker](https://gitcoin.co/issue/cennznet/grants/6/100025997?mutate_worker_action=reject&worker=wweagle09))_.**

I complete this task.. next i answer this question
**4) [definoob](https://gitcoin.co/definoob) has applied to start work _(Funders only: [approve worker](https://gitcoin.co/issue/cennznet/grants/6/100025997?mutate_worker_action=approve&worker=definoob) | [reject worker](https://gitcoin.co/issue/cennznet/grants/6/100025997?mutate_worker_action=reject&worker=definoob))_.**

My discord: Boy#3537
Let's have a talk
**5) [lukisoo](https://gitcoin.co/lukisoo) has applied to start work _(Funders only: [approve worker](https://gitcoin.co/issue/cennznet/grants/6/100025997?mutate_worker_action=approve&worker=lukisoo) | [reject worker](https://gitcoin.co/issue/cennznet/grants/6/100025997?mutate_worker_action=reject&worker=lukisoo))_.**

I would love to contribute to developing this project! I am also very interested in the areas of blockchain and NFTs so this would be a great opportunity to gain more experience more regarding these areas as well. My discord is lukisoo#6830 if you'd like to contact me and discuss this further :)
**6) [zhenglunsheng](https://gitcoin.co/zhenglunsheng) has applied to start work _(Funders only: [approve worker](https://gitcoin.co/issue/cennznet/grants/6/100025997?mutate_worker_action=approve&worker=zhenglunsheng) | [reject worker](https://gitcoin.co/issue/cennznet/grants/6/100025997?mutate_worker_action=reject&worker=zhenglunsheng))_.**

yes，let us see what will happy
**7) [leowxad](https://gitcoin.co/leowxad) has applied to start work _(Funders only: [approve worker](https://gitcoin.co/issue/cennznet/grants/6/100025997?mutate_worker_action=approve&worker=leowxad) | [reject worker](https://gitcoin.co/issue/cennznet/grants/6/100025997?mutate_worker_action=reject&worker=leowxad))_.**

I believe this project is nice.
**8) [stephinnoyewole](https://gitcoin.co/stephinnoyewole) has applied to start work _(Funders only: [approve worker](https://gitcoin.co/issue/cennznet/grants/6/100025997?mutate_worker_action=approve&worker=stephinnoyewole) | [reject worker](https://gitcoin.co/issue/cennznet/grants/6/100025997?mutate_worker_action=reject&worker=stephinnoyewole))_.**

Firstly, follow the project on Social media, such as Telegram, Facebook, twitter, Instagram, discord, Reddit, etc
Retweet twitter post and subscribe to YouTube page
**9) [mikyr](https://gitcoin.co/mikyr) has applied to start work _(Funders only: [approve worker](https://gitcoin.co/issue/cennznet/grants/6/100025997?mutate_worker_action=approve&worker=mikyr) | [reject worker](https://gitcoin.co/issue/cennznet/grants/6/100025997?mutate_worker_action=reject&worker=mikyr))_.**

Hola como podemos hacer que estas plataformas sean mas eficientes asegurando la mayor cantidad de recursos gracias
**10) [pedropony100](https://gitcoin.co/pedropony100) has applied to start work _(Funders only: [approve worker](https://gitcoin.co/issue/cennznet/grants/6/100025997?mutate_worker_action=approve&worker=pedropony100) | [reject worker](https://gitcoin.co/issue/cennznet/grants/6/100025997?mutate_worker_action=reject&worker=pedropony100))_.**

Hola como podemos hacer que estas plataformas sean mas eficientes asegurando la mayor cantidad de recursos gracias
**11) [ladykins](https://gitcoin.co/ladykins) has applied to start work _(Funders only: [approve worker](https://gitcoin.co/issue/cennznet/grants/6/100025997?mutate_worker_action=approve&worker=ladykins) | [reject worker](https://gitcoin.co/issue/cennznet/grants/6/100025997?mutate_worker_action=reject&worker=ladykins))_.**

Build the interface for Litho-Mart, a digital asset marketplace for the CENNZnet blockchain that allows users to search, view, store, buy and sell NFTs (collectible tokens).
This bounty includes the front-end design and implementation of the market interface.

Context
CENNZnet is a public blockchain and Decentralised Application platform that puts a great user experience first. CENNZnet needs an equally great interface for Litho, so that the creation of digital assets on the CENNZnet blockchain is seamless.
**12) [shad-k](https://gitcoin.co/shad-k) has been approved to start work.**

Hello, I am Frontend Engineer with 5+ years of experience building scalable, responsive and performant frontend web applications.
I am currently working on Litho Milestone 1 and would love to continue working  to complete Milestone 2 as well.
**13) [ssailsbury](https://gitcoin.co/ssailsbury) has applied to start work _(Funders only: [approve worker](https://gitcoin.co/issue/cennznet/grants/6/100025997?mutate_worker_action=approve&worker=ssailsbury) | [reject worker](https://gitcoin.co/issue/cennznet/grants/6/100025997?mutate_worker_action=reject&worker=ssailsbury))_.**

I am an award winning application developer with over a decade of experience in the graphics industry. 

Action Plan:

1. Design
2. Build
3. Implement

I look forward to becoming valuable member of this team and pushing this project above and beyond expectations.
**14) [bznid404](https://gitcoin.co/bznid404) has applied to start work _(Funders only: [approve worker](https://gitcoin.co/issue/cennznet/grants/6/100025997?mutate_worker_action=approve&worker=bznid404) | [reject worker](https://gitcoin.co/issue/cennznet/grants/6/100025997?mutate_worker_action=reject&worker=bznid404))_.**

Any sureprise? believe good in the market situation? i wait dev work again
**15) [danielfirpo](https://gitcoin.co/danielfirpo) has applied to start work _(Funders only: [approve worker](https://gitcoin.co/issue/cennznet/grants/6/100025997?mutate_worker_action=approve&worker=danielfirpo) | [reject worker](https://gitcoin.co/issue/cennznet/grants/6/100025997?mutate_worker_action=reject&worker=danielfirpo))_.**

Hello! My name is Daniel. 

I checked out your Medium article and the project seems awesome. I really like the idea of making NFTs more accessible to artists. I'd love to implement your design for you. 

As far building the project, I would use React. I would write clean and scalable code. I focus on professionalism while building projects, and would make sure to include tests written with Jest. 

I've worked on projects with teams as large as 20 members. While building these projects, I always enjoy being the one to make sure the final outcome matches the provided design document perfectly, in both functionality and appearance. I will do the same for your project, which should reduce the amount of iterations needed, and therefore the final result will be delivered sooner. 

You can check out my portfolio here: https://www.danielfirpo.com/

If you'd like to contact me with further questions you can email me at: danielfirpodev@gmail.com

Thanks!
**16) [1152061385](https://gitcoin.co/1152061385) has applied to start work _(Funders only: [approve worker](https://gitcoin.co/issue/cennznet/grants/6/100025997?mutate_worker_action=approve&worker=1152061385) | [reject worker](https://gitcoin.co/issue/cennznet/grants/6/100025997?mutate_worker_action=reject&worker=1152061385))_.**

I think the project is good for the community
**17) [yangbaba2021](https://gitcoin.co/yangbaba2021) has applied to start work _(Funders only: [approve worker](https://gitcoin.co/issue/cennznet/grants/6/100025997?mutate_worker_action=approve&worker=yangbaba2021) | [reject worker](https://gitcoin.co/issue/cennznet/grants/6/100025997?mutate_worker_action=reject&worker=yangbaba2021))_.**

the project is good for the community
**18) [systemfehler1979](https://gitcoin.co/systemfehler1979) has applied to start work _(Funders only: [approve worker](https://gitcoin.co/issue/cennznet/grants/6/100025997?mutate_worker_action=approve&worker=systemfehler1979) | [reject worker](https://gitcoin.co/issue/cennznet/grants/6/100025997?mutate_worker_action=reject&worker=systemfehler1979))_.**

Ich muss mich damit erst richtig befassen was hier mit überhaupt gemeint ist

Learn more [on the Gitcoin Issue Details page](https://gitcoin.co/issue/cennznet/grants/6/100025997).

**Comment by gitcoinbot** [comment]
@shad-k Hello from Gitcoin Core - are you still working on this issue? Please submit a WIP PR or comment back within the next 3 days or you will be removed from this ticket and it will be returned to an ‘Open’ status. Please let us know if you have questions!
* [x] reminder (3 days)
* [ ] escalation to mods (6 days)

Funders only: Snooze warnings for [1 day](https://gitcoin.co/issue/cennznet/grants/6/100025997?snooze=1) | [3 days](https://gitcoin.co/issue/cennznet/grants/6/100025997?snooze=3) | [5 days](https://gitcoin.co/issue/cennznet/grants/6/100025997?snooze=5) | [10 days](https://gitcoin.co/issue/cennznet/grants/6/100025997?snooze=10) | [100 days](https://gitcoin.co/issue/cennznet/grants/6/100025997?snooze=100)

**Comment by shad-k** [comment]
Will start work post Milestone 1 wrap up.

**Comment by shad-k** [comment]
With Milestone 1 work almost wrapped up, will start work on milestone 2 soon.

**Comment by gitcoinbot** [comment]
@shad-k Hello from Gitcoin Core - are you still working on this issue? Please submit a WIP PR or comment back within the next 3 days or you will be removed from this ticket and it will be returned to an ‘Open’ status. Please let us know if you have questions!
* [x] reminder (3 days)
* [ ] escalation to mods (6 days)

Funders only: Snooze warnings for [1 day](https://gitcoin.co/issue/cennznet/grants/6/100025997?snooze=1) | [3 days](https://gitcoin.co/issue/cennznet/grants/6/100025997?snooze=3) | [5 days](https://gitcoin.co/issue/cennznet/grants/6/100025997?snooze=5) | [10 days](https://gitcoin.co/issue/cennznet/grants/6/100025997?snooze=10) | [100 days](https://gitcoin.co/issue/cennznet/grants/6/100025997?snooze=100)

**Comment by shad-k** [comment]
Working on it.

**Comment by gitcoinbot** [comment]
@shad-k Hello from Gitcoin Core - are you still working on this issue? Please submit a WIP PR or comment back within the next 3 days or you will be removed from this ticket and it will be returned to an ‘Open’ status. Please let us know if you have questions!
* [x] reminder (3 days)
* [ ] escalation to mods (6 days)

Funders only: Snooze warnings for [1 day](https://gitcoin.co/issue/cennznet/grants/6/100025997?snooze=1) | [3 days](https://gitcoin.co/issue/cennznet/grants/6/100025997?snooze=3) | [5 days](https://gitcoin.co/issue/cennznet/grants/6/100025997?snooze=5) | [10 days](https://gitcoin.co/issue/cennznet/grants/6/100025997?snooze=10) | [100 days](https://gitcoin.co/issue/cennznet/grants/6/100025997?snooze=100)

**Comment by shad-k** [comment]
Waiting to wrap up milestone 1.

**Comment by gitcoinbot** [comment]
@shad-k Hello from Gitcoin Core - are you still working on this issue? Please submit a WIP PR or comment back within the next 3 days or you will be removed from this ticket and it will be returned to an ‘Open’ status. Please let us know if you have questions!
* [x] reminder (3 days)
* [ ] escalation to mods (6 days)

Funders only: Snooze warnings for [1 day](https://gitcoin.co/issue/cennznet/grants/6/100025997?snooze=1) | [3 days](https://gitcoin.co/issue/cennznet/grants/6/100025997?snooze=3) | [5 days](https://gitcoin.co/issue/cennznet/grants/6/100025997?snooze=5) | [10 days](https://gitcoin.co/issue/cennznet/grants/6/100025997?snooze=10) | [100 days](https://gitcoin.co/issue/cennznet/grants/6/100025997?snooze=100)

**Comment by shad-k** [comment]
Yes, working on this.

**Comment by gitcoinbot** [comment]
@shad-k Hello from Gitcoin Core - are you still working on this issue? Please submit a WIP PR or comment back within the next 3 days or you will be removed from this ticket and it will be returned to an ‘Open’ status. Please let us know if you have questions!
* [x] reminder (3 days)
* [ ] escalation to mods (6 days)

Funders only: Snooze warnings for [1 day](https://gitcoin.co/issue/cennznet/grants/6/100025997?snooze=1) | [3 days](https://gitcoin.co/issue/cennznet/grants/6/100025997?snooze=3) | [5 days](https://gitcoin.co/issue/cennznet/grants/6/100025997?snooze=5) | [10 days](https://gitcoin.co/issue/cennznet/grants/6/100025997?snooze=10) | [100 days](https://gitcoin.co/issue/cennznet/grants/6/100025997?snooze=100)

**Comment by shad-k** [comment]
Working on this.

**Comment by gitcoinbot** [comment]
@shad-k Hello from Gitcoin Core - are you still working on this issue? Please submit a WIP PR or comment back within the next 3 days or you will be removed from this ticket and it will be returned to an ‘Open’ status. Please let us know if you have questions!
* [x] reminder (3 days)
* [ ] escalation to mods (6 days)

Funders only: Snooze warnings for [1 day](https://gitcoin.co/issue/cennznet/grants/6/100025997?snooze=1) | [3 days](https://gitcoin.co/issue/cennznet/grants/6/100025997?snooze=3) | [5 days](https://gitcoin.co/issue/cennznet/grants/6/100025997?snooze=5) | [10 days](https://gitcoin.co/issue/cennznet/grants/6/100025997?snooze=10) | [100 days](https://gitcoin.co/issue/cennznet/grants/6/100025997?snooze=100)

**Comment by shad-k** [comment]
Working on some milestone 1 stuff for now

**Comment by gitcoinbot** [comment]
Issue Status: 1. Open 2. **Started** 3. Submitted 4. Done 

<hr>

__Work for 5000.0 DAI (5000.0 USD @ $1.0/DAI) has been submitted by__:

<hr>

* Learn more [on the Gitcoin Issue Details page](https://gitcoin.co/issue/cennznet/grants/6/100025997)
* Want to chip in? Add your own contribution [here](https://gitcoin.co/issue/cennznet/grants/6/100025997).
* Questions? Checkout <a href='https://gitcoin.co/help'>Gitcoin Help</a> or the <a href='https://discord.gg/gitcoin/'>Gitcoin's Discord</a>
* $6,222,217.37 more funded OSS Work available on the [Gitcoin Issue Explorer](https://gitcoin.co/explorer)

**Comment by gitcoinbot** [comment]
Issue Status: 1. Open 2. Started 3. **Submitted** 4. Done 

<hr>

__The funding of 5000.0 DAI (5000.0 USD @ $1.0/DAI)  attached to this issue has been approved & issued to @shad-k.__  

 
* Learn more [on the Gitcoin Issue Details page](https://gitcoin.co/issue/cennznet/grants/6/100025997)
* Questions? Checkout <a href='https://gitcoin.co/help'>Gitcoin Help</a> or the <a href='https://discord.gg/gitcoin/'>Gitcoin's Discord</a>
* $6,227,217.37 more funded OSS Work available on the [Gitcoin Issue Explorer](https://gitcoin.co/explorer)
